apiVersion: apps/v1
kind: Deployment
metadata:
  name: testflo-probe
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: testflo-probe
  template:
    metadata:
      labels:
        app: testflo-probe
    spec:
      containers:
      - name: probe
        image: alpine:3.19
        command: ["/bin/sh", "-c", "sleep 3600"]
