apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testflo-child
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ox79/testai.git
    targetRevision: main
    path: child
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
